export const content = {
  login: {
    alts: 'Atlassian',
    heading: 'Log in to continue',
    signup_head: 'Sign up to continue',
    continue: 'Or continue with',
    reg_email: 'Enter your email',
    place_email: 'Username',
    place_pass: 'Password',
    btn_content: 'Continue',
    btn_signup: 'Sign up',
    login_link: 'Already have an Atlassian account? Log in',
    register_link: 'Create an account',
    forgot_link: `Can't log in?`,
    back_login: 'Return to log in',
    recover: 'Send recovery link',
    google: 'Google',
    microsoft: 'Microsoft',
    apple: 'Apple',
    slack: 'Slack',
  },
};
